//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamMemb
    {
        public int FM_ID { get; set; }
        public string Account { get; set; }
        public int FB_ID { get; set; }
    
        public virtual FamList FamList { get; set; }
        public virtual Member Member { get; set; }
    }
}
